4. VisualStudio-C#/AplicacionDistribuida/CapaPresentacion/Models/ErrorViewModel.cs
namespace CapaPresentacion.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

4. VisualStudio-C#/AplicacionDistribuida/CapaPresentacion/Models/ViewModels/VMProyecto.cs
using CapaAccesoDatos.DataContext;

namespace CapaPresentacion.Models.ViewModels
{
    public class VMProyecto
    {
        public int Id { get; set; }

        public string? Nombre { get; set; }

        public string? Descripcion { get; set; }

        public string? FechaInicio { get; set; }

        public string? FechaFin { get; set; }

        public virtual ICollection<Tarea> Tareas { get; set; } = new List<Tarea>();
    }
}

4. VisualStudio-C#/AplicacionDistribuida/CapaPresentacion/Models/ViewModels/VMTarea.cs
using CapaAccesoDatos.DataContext;

namespace CapaPresentacion.Models.ViewModels
{
    public class VMTarea
    {
        public int Id { get; set; }

        public int ProyectoId { get; set; }

        public string? Nombre { get; set; }

        public string? Descripcion { get; set; }

        public string? Estado { get; set; }

        public string? AsignadoA { get; set; }

        public string? FechaInicio { get; set; }

        public virtual Proyecto Proyecto { get; set; } = null!;
    }
}

4. VisualStudio-C#/AplicacionDistribuida/CapaPresentacion/Controllers/TareaController.cs
using CapaAccesoDatos.DataContext;
using CapaPresentacion.Models;
using CapaPresentacion.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using CapaLogicaNegocio.Aplicacion;
using System.Globalization;

namespace CapaPresentacion.Controllers
{
    public class TareaController : Controller
    {
        private readonly ITareaApp _tareaApp;

        public TareaController(ITareaApp tareaApp)
        {
            _tareaApp = tareaApp;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            IQueryable<Tarea> queryTareaSQL = await _tareaApp.ObtenerTodos();

            List<VMTarea> lista = queryTareaSQL
                .Select(t => new VMTarea()
                {
                    Id = t.Id,
                    ProyectoId = t.ProyectoId,
                    Nombre = t.Nombre,
                    Descripcion = t.Descripcion,
                    Estado = t.Estado,
                    AsignadoA = t.AsignadoA,
                    FechaInicio = t.FechaInicio.Value.ToString("dd/MM/yyyy"),
                }).ToList(); 

            return StatusCode(StatusCodes.Status200OK, lista);
        }


        [HttpPost]
        public async Task<IActionResult> Insertar([FromBody] VMTarea modelo)
        {
            Tarea nuevaTarea = new Tarea()
            {
                ProyectoId = modelo.ProyectoId,
                Nombre = modelo.Nombre,
                Descripcion = modelo.Descripcion,
                Estado = modelo.Estado,
                AsignadoA = modelo.AsignadoA,
                FechaInicio = DateTime.ParseExact(modelo.FechaInicio, "dd/MM/yyyy", CultureInfo.CreateSpecificCulture("es-ECU")),
            };

            bool respuesta = await _tareaApp.Insertar(nuevaTarea);

            return StatusCode(StatusCodes.Status200OK, new { valor = respuesta });
        }

        [HttpPut]
        public async Task<IActionResult> Actualizar([FromBody] VMTarea modelo)
        {
            Tarea tareaActualizada = new Tarea()
            {
                Id = modelo.Id,
                ProyectoId = modelo.ProyectoId,
                Nombre = modelo.Nombre,
                Descripcion = modelo.Descripcion,
                Estado = modelo.Estado,
                AsignadoA = modelo.AsignadoA,
                FechaInicio = DateTime.ParseExact(modelo.FechaInicio, "dd/MM/yyyy", CultureInfo.CreateSpecificCulture("es-ECU")),
            };

            bool respuesta = await _tareaApp.Actualizar(tareaActualizada);

            return StatusCode(StatusCodes.Status200OK, new { valor = respuesta });
        }

        [HttpDelete]
        public async Task<IActionResult> Eliminar(int id)
        {
            bool respuesta = await _tareaApp.Eliminar(id);

            return StatusCode(StatusCodes.Status200OK, new { valor = respuesta });
        }
    }
}

4. VisualStudio-C#/AplicacionDistribuida/CapaPresentacion/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}


<div class="row">
    <div class="col-sm-12">

        <!--Inicio tarjeta-->
        <div class="card">
            <div class="card-header">Proyectos</div>
            <div class="card-body">

                <button class="btn btn-success" id="btnNuevo">Nuevo Proyecto</button>

                <hr />

                <table class="table table-striped" id="tbProyecto">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Descripcion</th>
                            <th>Fecha Inicio</th>
                            <th>Fecha Fin</th>
                            <th>Acciones</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>

            </div>
        </div>
        <!--Fin tarjeta-->

    </div>
</div>



<!--Inicio Modal-->
<div class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Detalle Proyecto</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="txtIdProyecto" value="0" />
                <div class="mb-2">
                    <label>Nombre</label>
                    <input type="text" class="form-control" id="txtNombre" />
                </div>
                <div class="mb-2">
                    <label>Descripcion</label>
                    <input type="text" class="form-control" id="txtDescripcion" />
                </div>
                <div class="mb-2">
                    <label>Fecha Inicio</label>
                    <input type="text" class="form-control" id="txtFechaInicio" />
                </div>
                <div class="mb-2">
                    <label>Fecha Fin</label>
                    <input type="text" class="form-control" id="txtFechaFin" />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnGuardar">Guardar</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<!--Fin Modal-->

@section Scripts {

    <script>

        const Modelo_base = {
            id : 0,
            nombre : "",
            descripcion : "",
            fechaInicio : "",
            fechaFin : ""
        }

        $(document).ready(() =>{

            listaProyectos();
        })

        function mostrarModal(modelo){

            $("#txtIdProyecto").val(modelo.id);
            $("#txtNombre").val(modelo.nombre)
            $("#txtDescripcion").val(modelo.descripcion)
            $("#txtFechaInicio").val(modelo.fechaInicio)
            $("#txtFechaFin").val(modelo.fechaFin)

            $('.modal').modal('show');
        }

        $("#btnNuevo").click(() => {

            mostrarModal(Modelo_base);
        })

        $("#btnGuardar").click(() => {
            let NuevoModelo = Modelo_base;

            NuevoModelo["id"] = $("#txtIdProyecto").val();
            NuevoModelo["nombre"]  = $("#txtNombre").val();
            NuevoModelo["descripcion"]  = $("#txtDescripcion").val();
            NuevoModelo["fechaInicio"]  = $("#txtFechaInicio").val();
            NuevoModelo["fechaFin"] = $("#txtFechaFin").val();

            if($("#txtIdProyecto").val() == "0"){
                fetch("Home/Insertar",{
                    method:"POST",
                    headers: {
                        'Content-Type': 'application/json;charset=utf-8'
                    },
                    body: JSON.stringify(NuevoModelo)
                })
                .then((response) => {
                    return response.ok ? response.json() : Promise.reject(response)
                })
                .then((dataJson) => {

                    if(dataJson.valor){
                        alert("registrado");
                          $('.modal').modal('hide');
                         listaProyectos();
                    }
                })
            }else{
                fetch("Home/Actualizar",{
                        method:"PUT",
                        headers: {
                            'Content-Type': 'application/json;charset=utf-8'
                        },
                        body: JSON.stringify( NuevoModelo)
                    })
                    .then((response) => {
                        return response.ok ? response.json() : Promise.reject(response)
                    })
                    .then((dataJson) => {

                        if(dataJson.valor){
                            alert("editado");
                              $('.modal').modal('hide');
                             listaProyectos();
                        }
                    })

            }

        })

        function listaProyectos(){

            fetch("Home/Lista")
            .then((response) => {
                return response.ok ? response.json() : Promise.reject(response)
            })
            .then((dataJson) => {

                $("#tbProyecto tbody").html("");

                dataJson.forEach((item) => {

                    $("#tbProyecto tbody").append(
                        $("<tr>").append(
                            $("<td>").text(item.nombre),
                            $("<td>").text(item.descripcion),
                            $("<td>").text(item.fechaInicio),
                            $("<td>").text(item.fechaFin),
                            $("<td>").append(
                                $("<button>").addClass("btn btn-primary btn-sm me-2 btn-editar").data("modelo",item).text("Editar"),
                                $("<button>").addClass("btn btn-danger btn-sm btn-eliminar").data("id",item.id).text("Eliminar")
                            )
                        )
                    )

                })


            })

        }

        $("#tbProyecto tbody").on("click",".btn-editar",function(){
            let Proyecto = $(this).data("modelo")

            mostrarModal(Proyecto)
        })


        $("#tbProyecto tbody").on("click",".btn-eliminar",function(){
            let id = $(this).data("id")

            let resultado = window.confirm("¿Desea eliminar el Proyecto?");


            if(resultado){


                  fetch("Home/Eliminar?id=" + id,{
                        method:"DELETE"
                    })
                    .then((response) => {
                        return response.ok ? response.json() : Promise.reject(response)
                    })
                    .then((dataJson) => {

                        if(dataJson.valor){
                             listaProyectos();
                        }
                    })
            }
        })
   </script>
}

4. VisualStudio-C#/AplicacionDistribuida/CapaPresentacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto Distribuidas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CapaPresentacion.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Proyecto Distribuidas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Proyectos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarea" asp-action="Index">Tareas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Proyecto Distribuidas Primer Parcial - <a asp-area="" asp-controller="" asp-action="">Privacidad</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

4. VisualStudio-C#/AplicacionDistribuida/CapaPresentacion/Views/Tarea/Index.cshtml
@{
    ViewData["Title"] = "Tarea";
}


<div class="row">
    <div class="col-sm-12">

        <!--Inicio tarjeta-->
        <div class="card">
            <div class="card-header">Tareas</div>
            <div class="card-body">

                <button class="btn btn-success" id="btnNuevo">Nueva Tarea</button>

                <hr />

                <table class="table table-striped" id="tbTarea">
                    <thead>
                        <tr>
                            <th>Proyecto ID</th>
                            <th>Nombre</th>
                            <th>Descripcion</th>
                            <th>Estado</th>
                            <th>Encargado</th>
                            <th>Fecha Inicio</th>
                            <th>Acciones</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>

            </div>
        </div>
        <!--Fin tarjeta-->

    </div>
</div>



<!--Inicio Modal-->
<div class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Detalle Tarea</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="txtIdTarea" value="0" />
                <div class="mb-2">
                    <label>Proyecto ID</label>
                    <input type="text" class="form-control" id="txtProyectoId" />
                </div>
                <div class="mb-2">
                    <label>Nombre</label>
                    <input type="text" class="form-control" id="txtNombre" />
                </div>
                <div class="mb-2">
                    <label>Descripcion</label>
                    <input type="text" class="form-control" id="txtDescripcion" />
                </div>
                <div class="mb-2">
                    <label>Estado</label>
                    <input type="text" class="form-control" id="txtEstado" />
                </div>
                <div class="mb-2">
                    <label>Encargado</label>
                    <input type="text" class="form-control" id="txtEncargado" />
                </div>
                <div class="mb-2">
                    <label>Fecha Inicio</label>
                    <input type="text" class="form-control" id="txtFechaInicio" />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnGuardar">Guardar</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<!--Fin Modal-->
@section Scripts {

    <script>

        const Modelo_base = {
            id: 0,
            proyectoId: 0,
            nombre: "",
            descripcion: "",
            estado: "",
            asignadoA: "",
            fechaInicio: ""
        }

        $(document).ready(() => {

            listaTareas();
        })

        function mostrarModal(modelo) {

            $("#txtIdTarea").val(modelo.id);
            $("#txtProyectoId").val(modelo.proyectoId);
            $("#txtNombre").val(modelo.nombre)
            $("#txtDescripcion").val(modelo.descripcion)
            $("#txtEstado").val(modelo.estado)
            $("#txtEncargado").val(modelo.asignadoA)
            $("#txtFechaInicio").val(modelo.fechaInicio)

            $('.modal').modal('show');
        }

        $("#btnNuevo").click(() => {

            mostrarModal(Modelo_base);
        })

        $("#btnGuardar").click(() => {
            let NuevoModelo = Modelo_base;

            NuevoModelo["id"] = $("#txtIdTarea").val();
            NuevoModelo["proyectoId"] = $("#txtProyectoId").val();
            NuevoModelo["nombre"] = $("#txtNombre").val();
            NuevoModelo["descripcion"] = $("#txtDescripcion").val();
            NuevoModelo["estado"] = $("#txtEstado").val();
            NuevoModelo["asignadoA"] = $("#txtEncargado").val();
            NuevoModelo["fechaInicio"] = $("#txtFechaInicio").val();

            if ($("#txtIdTarea").val() == "0") {
                fetch("Tarea/Insertar", {
                    method: "POST",
                    headers: {
                        'Content-Type': 'application/json;charset=utf-8'
                    },
                    body: JSON.stringify(NuevoModelo)
                })
                    .then((response) => {
                        return response.ok ? response.json() : Promise.reject(response)
                    })
                    .then((dataJson) => {

                        if (dataJson.valor) {
                            alert("registrado");
                            $('.modal').modal('hide');
                            listaTareas();
                        }
                    })
            } else {
                fetch("Tarea/Actualizar", {
                    method: "PUT",
                    headers: {
                        'Content-Type': 'application/json;charset=utf-8'
                    },
                    body: JSON.stringify(NuevoModelo)
                })
                    .then((response) => {
                        return response.ok ? response.json() : Promise.reject(response)
                    })
                    .then((dataJson) => {

                        if (dataJson.valor) {
                            alert("editado");
                            $('.modal').modal('hide');
                            listaTareas();
                        }
                    })

            }

        })

        function listaTareas() {

            fetch("Tarea/Lista")
                .then((response) => {
                    return response.ok ? response.json() : Promise.reject(response)
                })
                .then((dataJson) => {

                    $("#tbTarea tbody").html("");

                    dataJson.forEach((item) => {

                        $("#tbTarea tbody").append(
                            $("<tr>").append(
                                $("<td>").text(item.proyectoId),
                                $("<td>").text(item.nombre),
                                $("<td>").text(item.descripcion),
                                $("<td>").text(item.estado),
                                $("<td>").text(item.asignadoA),
                                $("<td>").text(item.fechaInicio),
                                $("<td>").append(
                                    $("<button>").addClass("btn btn-primary btn-sm me-2 btn-editar").data("modelo", item).text("Editar"),
                                    $("<button>").addClass("btn btn-danger btn-sm btn-eliminar").data("id", item.id).text("Eliminar")
                                )
                            )
                        )

                    })


                })

        }

        $("#tbTarea tbody").on("click", ".btn-editar", function () {
            let Tarea = $(this).data("modelo")

            mostrarModal(Tarea)
        })


        $("#tbTarea tbody").on("click", ".btn-eliminar", function () {
            let id = $(this).data("id")

            let resultado = window.confirm("¿Desea eliminar el Tarea?");


            if (resultado) {


                fetch("Tarea/Eliminar?id=" + id, {
                    method: "DELETE"
                })
                    .then((response) => {
                        return response.ok ? response.json() : Promise.reject(response)
                    })
                    .then((dataJson) => {

                        if (dataJson.valor) {
                            listaTareas();
                        }
                    })
            }
        })
    </script>
}